services:
  configurator:
    environment:
      DB_HOST: $app_db_host
      DB_PORT: $app_db_port
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=$app_db_admin_pass
      interval: 1s
      retries: 60
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_USER: $app_db_user
      MYSQL_PASSWORD: $app_db_pass
      MYSQL_ROOT_PASSWORD: $app_db_admin_pass
    volumes:
      - $app_dir_db_data:/var/lib/mysql
    networks:
      backend:

