version: "3"
services:
  app:
    image: mattermost/focalboard:7.8.0
    volumes:
      - $app_dir_data:/opt/focalboard/data
    environment:
      - VIRTUAL_HOST=$app_fqdn
      - VIRTUAL_PORT=$app_port
