networks:
  db:

services:

  hass:
    networks:
      db:

  mysql:
    image: mariadb:10.11
    volumes:
      # - $app_dir_db_conf:/var/lib/mysql
      - $app_dir_db_data:/var/lib/mysql
      - $app_dir_template/setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "${app_db_admin_pass}"
      MYSQL_DATABASE: "${app_db_name}"
      MYSQL_USER: "${app_db_user}"
      MYSQL_PASSWORD: "${app_db_pass}"

    networks:
      db:

