services:
  hydroqc2mqtt:
    environment:

      # See: https://hydroqc.ca/en/docs/configuration/environment/
      HQ2M_CONTRACTS_0_NAME: "${hydro_name}"
      HQ2M_CONTRACTS_0_USERNAME: "$hydro_username"
      HQ2M_CONTRACTS_0_PASSWORD: "$hydro_passwd"


      # Sur la facture en haut, Numero de Client: XXX XXX XXX => 0XXXXXXXXX
      # 10 digit ID, add leading zero if necessary
      HQ2M_CONTRACTS_0_CUSTOMER: '$hydro_customer'

      # Sur la facture en haut, Numero de Compte: XXX XXX XXX XXX => XXXXXXXXXXXX
      HQ2M_CONTRACTS_0_ACCOUNT: '$hydro_account'

      # Sur la facture sur le coté, chercher: Numéro de contrat, XXXX XXXXX => 0XXXXXXXXX
      # 10 digit ID, add leading zero if necessary
      HQ2M_CONTRACTS_0_CONTRACT: '$hydro_contract'

      HQ2M_CONTRACTS_0_SYNC_HOURLY_CONSUMPTION_ENABLED: "true"


      HQ2M_CONTRACTS_0_HOME_ASSISTANT_WEBSOCKET_URL: "$hass_url"
      HQ2M_CONTRACTS_0_HOME_ASSISTANT_TOKEN: "$hass_token"
